name: CI

on:
  push:
  pull_request:

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '>=1.18'

      - name: Setup Go linter
        run: go install golang.org/x/tools/cmd/goimports@latest && go install golang.org/x/lint/golint@latest

      - name: Setup moq
        run: go install github.com/matryer/moq@latest

      - name: Run checks
        run: make check

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '>=1.18'

      - name: Setup moq
        run: go install github.com/matryer/moq@latest

      - name: Run tests
        run: make test

      - name: Upload coverage report
        uses: codecov/codecov-action@v1.2.1
        with:
          file: coverage.txt
